enum HOME_MENU {THEME}
enum SCHEDULE_END_DRAWER {MAIN, CHOOSING}
enum TIMETABLE_END_DRAWER {MAIN, CHOOSING}
enum ROLE {ROLE_ADMIN, ROLE_SCHOOL_STUDENT, ROLE_SCHOOL_STUDENT_PARENT, ROLE_SCHOOL_TEACHER}
enum CHAT_MESSAGE_SEARCH_TYPE {BEFORE, AFTER}